INSERT INTO State_Hood(id, name, image, color) VALUES (0,'Galactic Empire', 'images/empire.jpg', 'BLACK');
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (0,'Sol', 0, 320.0, 695.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (1,'Proxima', 0, 360.0, 710.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (2,'Wolf', 0, 341.0, 668.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (3,'Ross', 0, 395.0, 741.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (4,'Leonis', 0, 431.0, 687.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (5,'Kanohi', 0, 461.0, 707.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (6,'Canton', 0, 465.0, 625.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (7,'New London', 0, 468.0, 604.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (8,'Dakota', 0, 416.0, 600.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (9,'Epsilon', 0, 382.0, 579.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (10,'Tau Ceti', 0, 354.0, 606.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (11,'Ceti', 0, 354.0, 629.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (12,'Eridani', 0, 322.0, 555.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (13,'Epsilon Ind', 0, 312.0, 568.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (14,'Altair', 0, 280.0, 590.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (15,'Sirius', 0, 301.0, 675.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (16,'Orion', 0, 280.0, 655.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (17,'Cooke', 0, 315.0, 731.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (18,'Regula', 0, 249.0, 730.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (19,'Kapteya', 0, 177.0, 725.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (20,'Ross 128', 0, 198.0, 757.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (21,'Beta Durani', 0, 269.0, 762.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (22,'Jericho', 0, 378.0, 779.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (23,'Signet', 0, 380.0, 809.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (24,'Deneb', 0, 390.0, 850.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (25,'Vega', 0, 520.0, 900.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (26,'Delphi', 0, 475.0, 801.0);

INSERT INTO State_Hood(id, name, image, color) VALUES (1,'Minbari Federation', 'images/minbari.png', 'BLUE');
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (27,'Norsa', 1, 485.0, 847.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (28,'Eudu', 1, 502.0, 869.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (29,'Muga', 1, 571.0, 890.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (30,'Tychola', 1, 642.0, 880.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (31,'Tir', 1, 659.0, 843.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (32,'Zendamor', 1, 619.0, 830.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (33,'Klath', 1, 560.0, 820.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (34,'Eshar', 1, 608.0, 791.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (35,'Davala Than', 1, 710.0, 815.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (36,'Sorpigal', 1, 775.0, 771.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (37,'Tavalan', 1, 644.0, 770.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (38,'Nocalo', 1, 503.0, 787.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (39,'Pagati', 1, 538.0, 761.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (40,'Shengol', 1, 548.0, 738.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (41,'Minbar', 1, 565.0, 715.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (42,'Tr`Es`Na', 1, 562.0, 656.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (43,'Solta Gan', 1, 590.0, 676.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (44,'Drala Toth', 1, 580.0, 615.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (45,'Valusha', 1, 609.0, 623.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (46,'Trigati', 1, 660.0, 645.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (47,'Sh`Lekk`Tha', 1, 542.0, 560.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (48,'Ralafe', 1, 627.0, 730.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (49,'Tala', 1, 662.0, 702.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (50,'Tro`Kact', 1, 690.0, 690.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (51,'Thessa', 1, 694.0, 727.0);

INSERT INTO State_Hood(id, name, image, color) VALUES (2,'Centauri Republic', 'images/centauri.png', 'BLUEVIOLET');
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (52,'Batain', 2, 537.0, 667.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (53,'Courtor', 2, 482.0, 637.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (54,'Beta 3', 2, 462.0, 577.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (55,'Gorash', 2, 517.0, 498.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (56,'Cargan', 2, 555.0, 538.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (57,'Beta 2', 2, 598.0, 578.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (58,'Bentat', 2, 670.0, 580.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (59,'Alpha 1', 2, 730.0, 609.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (60,'Entat', 2, 730.0, 428.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (61,'Elatta', 2, 665.0, 514.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (62,'Centauri Prime', 2, 622.0, 475.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (63,'Rogoth', 2, 623.0, 423.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (64,'Alpha 2', 2, 637.0, 410.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (65,'Marigol', 2, 636.0, 371.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (66,'Quadrant 8', 2, 628.0, 335.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (67,'Polgrath', 2, 639.0, 301.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (68,'Lux Prime', 2, 566.0, 310.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (69,'Quadrant 17', 2, 487.0, 323.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (70,'Quadrant 32', 2, 458.0, 409.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (71,'Quadrant 27', 2, 375.0, 435.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (72,'Quadrant 1', 2, 355.0, 474.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (73,'Ragesh', 2, 468.0, 488.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (74,'Immolan', 2, 561.0, 479.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (75,'Amoh', 2, 528.0, 427.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (76,'Tolnania', 2, 573.0, 392.0);

INSERT INTO State_Hood(id, name, image, color) VALUES (3,'Narn Regime', 'images/narn.png', 'RED');
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (77,'Quadrant 14', 3, 391.0, 491.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (78,'Quadrant 24', 3, 440.0, 436.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (79,'Quadrant 37', 3, 546.0, 400.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (80,'T`Lin', 3, 440.0, 350.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (81,'Maruth', 3, 350.0, 360.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (82,'Quadrant 7', 3, 280.0, 355.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (83,'Carridun', 3, 230.0, 365.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (84,'Tachuno', 3, 302.0, 380.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (85,'Sorith', 3, 255.0, 391.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (86,'Ardun', 3, 225.0, 421.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (87,'Bargoth', 3, 278.0, 421.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (88,'Prumith', 3, 320.0, 438.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (89,'Binan', 3, 280.0, 493.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (90,'Sigma', 3, 152.0, 530.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (91,'Narn', 3, 280.0, 546.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (92,'Una San', 3, 260.0, 575.0);
INSERT INTO Star_System(id, name, statehood_id, coordinateX, coordinateY) VALUES (93,'Kotok', 3, 300.0, 588.0);